Fix Stronghold boxes
ZeroK-RTS/Zero-K pull request #4353
Opened 2021-03-16 22:25 UTC by Arch-Shaman

Fixes #4300

Big Teams (5v5+)
https://cdn.discordapp.com/attachments/278908415756206080/821508130084093972/unknown.png

Small Teams (3v3 - 5v5)
https://cdn.discordapp.com/attachments/278908415756206080/821507824504668260/unknown.png

1v1 - 2v2
https://cdn.discordapp.com/attachments/278908415756206080/821505157400494110/unknown.png

Also tries to add ffa boxes

2021-03-16 23:43 UTC, sprunk commented on LuaRules/Configs/StartBoxes/Stronghold_beta.lua
> +	if players > 4 then
Why not use `Spring.Utilities.Gametype.isSmallTeams` (and `isBigTeams`)?

2021-03-16 23:43 UTC, sprunk commented on LuaRules/Configs/StartBoxes/Stronghold_beta.lua
> +	return boxes, {4}
What about 8-way?

2021-03-16 23:43 UTC, sprunk commented on LuaRules/Configs/StartBoxes/Stronghold_beta.lua
> +
The big teams version should probably be just "east" and "west".

2021-03-17 07:21 UTC, sprunk requested changes
Boxes are indexed from 0

2021-03-17 07:25 UTC, sprunk commented on LuaRules/Configs/StartBoxes/Stronghold_beta.lua
> +else -- 8 way FFA.
If you return all 8 boxes for any FFA, the 4-way risks using some corner boxes and some with the geos. While boxes don't need to be fair if we're cramming more people than there are equal start positions, they still should if we can afford it.

Make 4-way either use the corners or the geos (doesn't matter which, can even be random)

2021-03-17 08:49 UTC, Arch-Shaman commented on LuaRules/Configs/StartBoxes/Stronghold_beta.lua
> +else -- 8 way FFA.
alright on it.

2021-03-18 00:28 UTC, Arch-Shaman commented on LuaRules/Configs/StartBoxes/Stronghold_beta.lua
> +else -- 8 way FFA.
3476e9a (resolves?)

2021-03-18 03:12 UTC, Arch-Shaman commented
> Boxes are indexed from 0

Is this still applicable? Do I need to redo everything with index 0?

2021-03-19 05:28 UTC, sprunk commented on LuaRules/Configs/StartBoxes/Stronghold_beta.lua
> +end
```suggestion
local teamcount = Spring.Utilities.GetTeamCount()
```

2021-03-19 05:31 UTC, sprunk commented on LuaRules/Configs/StartBoxes/Stronghold_beta.lua
> +			boxes[0].boxes[1] = team5box
seems to have incorrect names?

2021-03-19 23:39 UTC, Arch-Shaman commented on LuaRules/Configs/StartBoxes/Stronghold_beta.lua
> +			boxes[0].boxes[1] = team5box
You're right. Good catch. Should be i + 1

2021-03-30 08:53 UTC, Arch-Shaman commented
I did something wrong somewhere..

2021-03-30 14:06 UTC, sprunk commented
I expect to have the time to actually test this after 04-07.

2021-03-30 23:56 UTC, Arch-Shaman commented
Error: [LuaRules::RunCallInTraceback] error=2 (LUA_ERRRUN) callin=LoadCode trace=[Internal Lua error: Call failure] [LuaVFS::Include(synced=1)][pcall] file=LuaRules/gadgets.lua error=2 ([LuaVFS::Include(synced=1)][pcall] file=LuaRules/Configs/StartBoxes/Stronghold V4.lua error=2 ([LuaVFS::Include(synced=1)][pcall] file=LuaRules/Configs/StartBoxes/Stronghold_beta.lua error=2 ([string "LuaRules/Configs/StartBoxes/Stronghold_beta..."]:1119: attempt to index field '?' (a nil value)) ptop=1 cenv=0) ptop=2 cenv=1) ptop=3 cenv=0
stack traceback:
    [C]: in function 'Include'
    [string "LuaRules/draw.lua"]:15: in main chunk

2021-03-30 23:57 UTC, Arch-Shaman commented
I didn't reindex the initiator part.

2021-04-10 21:38 UTC, merged