CAI Adjustments
ZeroK-RTS/Zero-K pull request #4589
Opened 2022-01-07 09:23 UTC by Mach565

Removed some unused units from one file, and in addition CAI has some more build options.

2022-01-07 10:26 UTC, sprunk approved these changes

2022-01-07 11:41 UTC, Mach565 commented
Been trying to test it out, but CAI isn't doing anything, no idea why.

2022-01-07 11:43 UTC, sprunk requested changes
i'll check it in about 24 hours

2022-01-08 02:38 UTC, sprunk commented on LuaRules/Configs/cai/buildtasks.lua
> +					count = 3,
?

2022-01-08 02:38 UTC, Mach565 commented on LuaRules/Configs/cai/buildtasks.lua
> +					count = 3,
forgot to change it back, my bad

2022-01-08 02:38 UTC, Mach565 commented
Fixed the issue. Non-bombers in the bombers category breaks the AI and stops it from doing anything.

2022-03-26 20:27 UTC, sprunk approved these changes
Looks okay but let GF have a look too.

2022-03-26 22:02 UTC, merged