Unhardcode nuke and antinukes from the antinuke gadget
ZeroK-RTS/Zero-K pull request #4590
Opened 2022-01-07 09:49 UTC by Mach565

Not sure how this was missed in the initial unhardcoding, but here it is.

2022-01-07 10:04 UTC, sprunk commented on units/staticnuke.lua
> +    isNuke = true,
I am scared of uppercase.

2022-01-07 10:32 UTC, sprunk requested changes
`is_nuke`, also missing the UI part.

2022-01-07 10:40 UTC, Mach565 commented
> `is_nuke`, also missing the UI part.

UI part?

2022-01-07 10:42 UTC, sprunk commented
> UI part?

The widget that draws the green and red lines and circles when aiming a nuke.

2022-01-08 04:04 UTC, sprunk commented
Looks blind and untested.

2022-01-08 04:05 UTC, merged