more better randomness for wind turbine/tidal gen
ZeroK-RTS/Zero-K pull request #4649
Opened 2022-03-07 20:18 UTC by SteelBlueZK

math.random() will return a real number, but math.random() with
arguments returns only int eg. args (-0.5,0.5) the result will
always be 0.

Wind turbine randomness in stable a little less random than probably intended due to above. Also, in tidal form cradle no longer double turned by random value and is given randomness.

2022-03-10 23:30 UTC, sprunk commented on scripts/energywind.lua
> +		tideDirection = tideDirection + math.random() - 0.5 * math.rad(2)
Right now this line increments the direction value by between 0.0 and 1.0 radians (i.e. up to 57ish degrees with an average of 28ish) and then decrements by 1 degree (i.e. half of two degrees) for an average change of 27ish. This is much faster than the turn speed of 1 degree/s can keep up (the direction target runs circles around the turbine).

I believe this was supposed to be
```suggestion
		tideDirection = tideDirection + (math.random() - 0.5) * math.rad(2)
```
On the other hand not keeping up looks marginally better in that it keeps swaying while the "fixed" version will turn (for example) 0.3 degrees in 300ms, then stop for the remaining 700ms of a cycle. Perhaps save the random roll in a variable and scale the speed accordingly as well?

2022-03-10 23:33 UTC, sprunk requested changes
See comment.

2022-03-24 03:11 UTC, SteelBlueZK commented on scripts/energywind.lua
> +		tideDirection = tideDirection + math.random() - 0.5 * math.rad(2)
Thanks for the find.

2022-03-24 12:02 UTC, sprunk commented on scripts/energywind.lua
> +		spinSpeed = math.max(-waterMaxSpin),math.min(waterMaxSpin, 0.99*spinSpeed + (math.random() - 0.5) / 100))
Looks incorrect:
```suggestion
		spinSpeed = math.max(-waterMaxSpin, math.min(waterMaxSpin, 0.99*spinSpeed + (math.random() - 0.5) / 100)))
```

But also, `0.99*spinSpeed + (math.random() - 0.5) / 100)` will never put `spinSpeed` beyond 1. Maybe it could be tweaked so that the min/max calls aren't needed (keeping in mind 1 radian is ~57 degrees).

2022-03-24 22:46 UTC, SteelBlueZK commented
TODO: better maths on this. I'll also look into how expensive math.min/math.max are in comparison to lua number math.

It might be an option to make it sway back and forth in a +- 60 degree range from the randomly defined baseDirection heading, which would be Turn().

2022-08-16 01:52 UTC, merged