Optionally show WHR ratings in Tab Window
ZeroK-RTS/Zero-K pull request #4671
Opened 2022-04-10 14:28 UTC by jklw

Hi, my username in the game is "dunno".

Previous forum post: https://zero-k.info/Forum/Thread/34990

It can't display the rating of players who joined after the start; I think that would require adding the rating to the `MidGameJoinUser` message:

https://github.com/ZeroK-RTS/Zero-K-Infrastructure/blob/9da8b2369c9d63e87ff4ab779f6f54cc45090c44/Shared/LobbyClient/DedicatedServer.cs#L75

2022-04-11 14:44 UTC, sprunk requested changes

2022-04-11 14:44 UTC, sprunk commented on LuaUI/Widgets/gui_chili_share.lua
> +local zeroIfNumWrhDisabled = 0
Weird name. Also consider a proper type and apply logic later:
```suggestion
local whrEnabled = false
```
and then later:
```diff
- stuff + zeroIfNumWrhDisabled * whrWidth
+ stuff + (whrEnabled and whrWidth or 0)
```

2022-04-11 14:44 UTC, sprunk commented on LuaUI/Widgets/gui_chili_share.lua
> +SetWantRebuild_ = SetWantRebuild
Just move the definition of `SetWantRebuild` above the first use. Alternatively if there's ugliness and/or circular dependency then forward-declare the actual function.

2022-04-11 23:41 UTC, jklw commented on LuaUI/Widgets/gui_chili_share.lua
> +local zeroIfNumWrhDisabled = 0
Was trying to keep the usage of Lua's somewhat dangerous replacement for the ternary operator in 1 place (actually 2), but ok :)

2022-04-11 23:59 UTC, jklw commented on LuaUI/Widgets/gui_chili_share.lua
> +SetWantRebuild_ = SetWantRebuild
Lua lob here; was following the precedent in that file (`UpdateListFunction = Buildme`, but without the change of name ;)).

Moving would require moving lots of existing code to above the options.

I tried forward-declaring `local SetWantRebuild` on top and removing the highlighted line (and obviously, changing the call in `OnChange` to `SetWantRebuild()`); that strangely doesn't work (see error below. If `SetWantRebuild` is nil at that point, my version shouldn't work either, but somehow it does?).


```
[t=00:01:31.372525][f=0008188] Chili-Error in `Show current WHR (Elo) rating of players` (couldn't detect the owner widget): [string "LuaUI/Widgets/gui_chili_share.lua"]:124: attempt to call upvalue 'SetWantRebuild' (a nil value)
[t=00:01:31.372600][f=0008188] stacktrace:
	[string "LuaUI/Widgets/gui_chili_share.lua"]:124: in origOnChange
	[string "LuaUI/Widgets/gui_epicmenu.lua"]:1342: in origOnChange
	[string "LuaUI/Widgets/gui_epicmenu.lua"]:1178: in eventListener
	[string "LuaUI/Widgets/chili_old/controls/object.lua"]:631: in CallListeners
	...
	(tail call): in [?]
	[string "LuaUI/Widgets/chili_old/controls/screen.lua"]:233
```

2022-04-12 00:00 UTC, jklw commented on LuaUI/Widgets/gui_chili_share.lua
> +		name    = "Chili Share menu v1.25",
Done

2022-04-12 00:00 UTC, jklw commented on LuaUI/Widgets/gui_chili_share.lua
> +		rating = pdata.elo
Done

2022-04-12 00:00 UTC, jklw commented on LuaUI/Widgets/gui_chili_share.lua
> +	["1"] = {1  ,   0 ,   0,  1},
Done

2022-04-14 14:39 UTC, jklw commented on LuaUI/Widgets/gui_chili_share.lua
> +SetWantRebuild_ = SetWantRebuild
To be clear, I've left this unchanged (using `SetWantRebuild_`) in the commit below, which works. So this PR should be functionally mergeable.

2022-04-15 02:52 UTC, GoogleFrog commented
I think options at the bottom of widgets can make a lot of sense. See integral menu.

2022-04-15 02:52 UTC, merged

2022-04-15 03:01 UTC, GoogleFrog commented on LuaUI/Widgets/gui_chili_share.lua
> +SetWantRebuild_ = SetWantRebuild
@jklw for the future, don't learn precedents from this widget. Rebuilding as much as it does is bad, things like `UpdateListFunction = Buildme` are bad. Most of the other chili widgets are written in a better style.