Added a gadget to unstick caretakers
ZeroK-RTS/Zero-K pull request #4681
Opened 2022-04-21 04:19 UTC by Arch-Shaman

Caretakers occasionally will get stuck reclaiming (typically when they catch onto a flying wreck) something out of range. This gadget introduces a 2hz check for if a feature (or unit) is range of a caretaker.

2022-04-21 10:32 UTC, sprunk requested changes

2022-04-21 10:32 UTC, sprunk commented on LuaRules/Gadgets/unit_unstick_staticcon.lua
> +			handled[f + delay] = handled[f + delay] or {} -- check back in 15 frames.
Why build the table from scratch? `handled[f + delay] = handled[f]` and remove anything that died. Better yet, nanos are rare enough that it would be fine not to have a per-frame table and just a single iteratable map.

2022-04-21 17:37 UTC, Arch-Shaman commented on LuaRules/Gadgets/unit_unstick_staticcon.lua
> +			handled[f + delay] = handled[f + delay] or {} -- check back in 15 frames.
Attempted optimization for FW as players are expected to build both rejuv (static repairer, probably less rare) and caretaker. Figured it would be less of a perf hit this way, though admittedly this is poorly understood. I just submitted the first working draft for FW. I'll update it to use iterable map. 

I'd like to know if I should do the same for my copy in FW since there's expected to be more static cons.

2022-04-21 18:00 UTC, sprunk commented on LuaRules/Gadgets/unit_unstick_staticcon.lua
> +			handled[f + delay] = handled[f + delay] or {} -- check back in 15 frames.
Iterable map should be faster, regardless of what unit types there are (ie. still fastest in your mod when rejuv exists) or how many of each type get built (ie. still fastest if people build 9001 rejuvs and caretakers). A caveat is that it may disallow removal of dead units during iteration but `UnitFinished` and `UnitReverseBuilt` should be used for that regardless.

2022-04-21 18:22 UTC, Arch-Shaman commented on LuaRules/Gadgets/unit_unstick_staticcon.lua
> +		date      = "4-20-2022",
Any particular reason for this format, out of curiosity?

2022-04-21 18:38 UTC, Arch-Shaman commented on LuaRules/Gadgets/unit_unstick_staticcon.lua
> +	end
Will Echo(x, y) would work the DebugEcho func here?

2022-04-21 19:02 UTC, sprunk commented on LuaRules/Gadgets/unit_unstick_staticcon.lua
> +	spEcho("[unit_staticcon_unsticker]: " .. str)
```suggestion
local function DebugEcho(...)
	spEcho("[unit_staticcon_unsticker]", unpack(arg))
```

2022-04-21 19:03 UTC, sprunk commented on LuaRules/Gadgets/unit_unstick_staticcon.lua
> +	end
Right, `DebugEcho` needs to support it. See the comment above at that func

2022-04-21 19:03 UTC, sprunk commented on LuaRules/Gadgets/unit_unstick_staticcon.lua
> +		date      = "4-20-2022",
That is the international standard when writing dates using numbers-with-dashes ( https://en.wikipedia.org/wiki/ISO_8601 ). Feel free to use something like "April 20th, 2022" if you want the month in front though.

2022-04-21 19:15 UTC, sprunk commented on LuaRules/Gadgets/unit_unstick_staticcon.lua
> +	return math.sqrt(((x2 - x) * (x2 - x)) + ((z2 - z) * (z2 - z)))
```suggestion
	return (x2 - x)^2 + (z2 - z)^2
```

2022-04-21 19:33 UTC, Arch-Shaman commented on LuaRules/Gadgets/unit_unstick_staticcon.lua
> +		date      = "4-20-2022",
No need, just wanted to know the why behind it. Updated.

2022-04-21 21:08 UTC, Arch-Shaman commented on LuaRules/Gadgets/unit_unstick_staticcon.lua
> +			handled[f + delay] = handled[f + delay] or {} -- check back in 15 frames.
That's fine with me. I'll update both versions to use it.

2022-04-21 21:21 UTC, Arch-Shaman commented on LuaRules/Gadgets/unit_unstick_staticcon.lua
> +			handled[f + delay] = handled[f + delay] or {} -- check back in 15 frames.
Added iterablemap.

2022-05-13 21:50 UTC, Arch-Shaman commented
Untested, but setting to ready for review for now. The FW version is relatively stable, but i'd need to do testing in zk.

2022-05-22 02:56 UTC, GoogleFrog commented on LuaRules/Gadgets/unit_unstick_staticcon.lua
> +local function GetDistance(unitID, targetID, isReclaim)
GetDistanceSq

2022-05-22 02:58 UTC, GoogleFrog commented on LuaRules/Gadgets/unit_unstick_staticcon.lua
> +		for id, _ in pairs(IterableMap.Iterator(handled)) do
Iterator is slow. Use Apply. Also, doesn't Iterator work without putting it in a pairs?

2022-05-22 02:59 UTC, GoogleFrog commented on LuaRules/Gadgets/unit_unstick_staticcon.lua
> +	if debug then DebugEcho(unitID .. ": ", cmdID, cmdParam1, cmdParam2) end
Whitespace, missing newline after then.

2022-05-22 03:02 UTC, GoogleFrog commented on LuaRules/Gadgets/unit_unstick_staticcon.lua
> +		for id, _ in pairs(IterableMap.Iterator(handled)) do
ApplyFraction would be even better.

2022-05-22 03:49 UTC, GoogleFrog commented
`for id, _ in pairs(IterableMap.Iterator(handled)) do` simply crashes. How does this work in FW?

The gadget does not work through luarules reload.

2022-05-22 03:52 UTC, GoogleFrog commented on LuaRules/Gadgets/unit_unstick_staticcon.lua
> +	spEcho("[unit_staticcon_unsticker]", unpack(arg))
This simply crashes.

2022-05-22 04:05 UTC, merged