Improving Starlight laser handling
ZeroK-RTS/Zero-K pull request #4684
Opened 2022-04-24 23:50 UTC by danfireman

2022-04-25 00:04 UTC, sprunk requested changes
minor technicalities

2022-04-25 00:04 UTC, sprunk commented on LuaUI/Widgets/unit_starlight_targetting.lua
> +		if (unitDefID == Starlight_ID)
see line 31-32
```suggestion
		if (unitDefID == StarlightUnitDefID)
```

2022-04-25 00:04 UTC, sprunk commented on LuaUI/Widgets/unit_starlight_targetting.lua
> +local Starlight_ID = UnitDefNames.mahlazer.id
Same as the next line, drop
```suggestion
```

2022-04-25 00:04 UTC, sprunk commented on LuaUI/Widgets/unit_starlight_targetting.lua
> +	currentTarget,
comment out (atm it's referencing some random nil globals)
```suggestion
	-- unitID, pos, targetPos, currentTarget
```

2022-04-25 09:14 UTC, GoogleFrog commented
I dislike metatables. Are functions being copied multiple times here? I don't see what would be wrong with declaring a bunch of local functions and passing simple tables of local data to them. The handling part of the widget could even be cleaned up with IterableMap.

2022-04-25 09:16 UTC, GoogleFrog commented on LuaUI/Widgets/unit_starlight_targetting.lua
> +					local dist = sqdist(self.targetPos, {x,y,z})
This also spams a lot of tables.

2022-04-25 22:29 UTC, danfireman commented on LuaUI/Widgets/unit_starlight_targetting.lua
> +		GiveOrderToUnit(self.unitID,CMD_STOP, {}, {""},1)
I copy-pasted this from somewhere. Shall change to 0

2022-04-25 22:30 UTC, danfireman commented on LuaUI/Widgets/unit_starlight_targetting.lua
> +					local dist = sqdist(self.targetPos, {x,y,z})
Not too sure I follow. Are you disliking the `{x,y,z}`?

2022-04-25 22:48 UTC, danfireman commented on LuaUI/Widgets/unit_starlight_targetting.lua
> +		GiveOrderToUnit(self.unitID,CMD_STOP, {}, {""},1)
Done

2022-04-27 18:37 UTC, danfireman commented
> I dislike metatables. Are functions being copied multiple times here? I don't see what would be wrong with declaring a bunch of local functions and passing simple tables of local data to them. The handling part of the widget could even be cleaned up with IterableMap.

Note that I've changed this now.

2022-05-22 02:54 UTC, GoogleFrog commented
Why was bait_level_default removed?

2022-05-22 05:10 UTC, GoogleFrog commented
![spring_2022-05-22_15-04-59](https://user-images.githubusercontent.com/1318249/169679787-ede8bab3-2de3-482b-bb36-4808001febdc.gif)
The widget is now fine technically, but I'm not happy with how poorly it works with latency. I'd at least want an easy way to disable it (perhaps by checking anti-bait state?).

2022-05-22 06:21 UTC, closed without merging