Better lava high ground boxes
ZeroK-RTS/Zero-K pull request #4731
Opened 2022-07-21 21:17 UTC by Arch-Shaman

![image](https://user-images.githubusercontent.com/48730089/180316585-6d8f65a3-5059-412e-b7b1-f6a6fcc2b93e.png)

2022-07-21 21:43 UTC, sprunk requested changes

2022-07-21 21:43 UTC, sprunk commented on LuaRules/Configs/StartBoxes/Lava Highground 2.11.lua
> +boxes[1] = {startpoints = {}, boxes = {}, nameLong = "Lava Lovers", nameShort = "Lava"}
Do the boring old "North" and "South" etc.


(also, should have been "Magma Maniacs" if anything)

2022-07-21 21:43 UTC, sprunk commented on LuaRules/Configs/StartBoxes/Lava Highground 2.11.lua
> +		boxes[0].startpoints = {start1, start2}
Diagonally crossed boxes sound bad, remove.

2022-07-21 21:43 UTC, sprunk commented on LuaRules/Configs/StartBoxes/Lava Highground 2.11.lua
> +	elseif r == 4 then
Same as `r == 3` after shuffling, remove.

2022-07-21 21:43 UTC, sprunk commented on LuaRules/Configs/StartBoxes/Lava Highground 2.11.lua
> +	elseif r == 5 then
Same as `r == 2` after shuffling, remove.

2022-07-21 21:43 UTC, sprunk commented on LuaRules/Configs/StartBoxes/Lava Highground 2.11.lua
> +	else
Same as `r == 1` after shuffling, remove.

2022-07-21 22:10 UTC, Arch-Shaman commented on LuaRules/Configs/StartBoxes/Lava Highground 2.11.lua
> +	else
Think i got that one. It's hard to tell.

2022-07-22 10:39 UTC, sprunk commented on LuaRules/Configs/StartBoxes/Lava Highground 2.11.lua
> +		boxes[0].nameShort = "N"
the FFA config says box1 is South-west and box3 is South-east but the teams config says box 1+3 is North?

2022-07-22 10:39 UTC, sprunk commented on LuaRules/Configs/StartBoxes/Lava Highground 2.11.lua
> +		boxes[1].boxes = {box2, box3}
Needs "East" and "West" added

2022-07-22 10:40 UTC, sprunk commented on LuaRules/Configs/StartBoxes/Lava Highground 2.11.lua
> +		boxes[1].nameShort = "SW"
FFA conf. says box2 is North-East

2022-07-22 10:40 UTC, sprunk commented on LuaRules/Configs/StartBoxes/Lava Highground 2.11.lua
> +		boxes[0].nameLong = "Northeast"
FFA conf says box1 is southwest

2022-07-22 10:42 UTC, sprunk commented on LuaRules/Configs/StartBoxes/Lava Highground 2.11.lua
> +	r = math.random(1, 6)
this effectively emulates shuffle, could just return all 4 boxes (basically the same as FFA) since all-shuffle is the default for small teams and duels

2022-07-24 18:54 UTC, Arch-Shaman commented on LuaRules/Configs/StartBoxes/Lava Highground 2.11.lua
> +	r = math.random(1, 6)
I'm not fully sure I understand this comment's action recommendation. Could you explain it in more detail?

2022-07-31 01:49 UTC, sprunk commented on LuaRules/Configs/StartBoxes/Lava Highground 2.11.lua
> +	r = math.random(1, 6)
For FFA, the config returns all 4 boxes. The shuffle modoption will then randomly pick 2.

Your "math.random(1,6) etc" code has 4 boxes to choose from and randomly picks 2, then returns them. This replicates what shuffle does with the FFA 4-box config, except worse, because you can no longer get non-random boxes by setting the modoption to off.

2022-07-31 01:50 UTC, merged