unit_initial_queue.lua FIX duplicate msg to spec and ignoring remove msg
ZeroK-RTS/Zero-K pull request #5152
Opened 2024-01-04 14:16 UTC by Helwor

-Removed server msg sent with 's',
  spectator in any view mode receive allied message in pregame
-Code was faulty, would never receive remove message

2024-01-06 01:59 UTC, sprunk requested changes

2024-01-06 01:59 UTC, sprunk commented on LuaUI/Widgets/unit_initial_queue.lua
> +end
> Error: Failed to load: unit_initial_queue.lua, [string "LuaUI/Widgets/unit_initial_queue.lua"]:420: '<eof>' expected near 'end'
```suggestion
```

2024-01-06 01:59 UTC, sprunk commented on LuaUI/Widgets/unit_initial_queue.lua
> +		local typeArg, unitDefIDorIndex = tonumber(msgArray[1]), tonumber(msgArray[2])
`unitDefIDorIndex` makes the code somewhat hard to read and to keep track of whether it's one or the other. Perhaps do it like this (conceptually and not necessarily verbatim)?
```lua
local typeArg = tonumber(msgArray[1])

if typeArg == 5 then
  -- blabla
  return
end

if typeArg == 2 then
  local index = tonumber(msgArray[2])
  -- blabla
  return
end

if typeArg == 1 or typeArg == 3 or typeArg == 4 then
  local unitDefID = tonumber(msgArray[2])
  -- rest as-is
end
```

2024-01-07 06:27 UTC, Helwor commented
done

2024-01-15 05:17 UTC, merged

2024-01-15 05:23 UTC, sprunk commented
tested, works as advertised. thanks!