add guard selection rank override.
ZeroK-RTS/Zero-K pull request #5278
Opened 2024-05-20 22:09 UTC by amnykon

2024-05-21 00:48 UTC, sprunk requested changes

2024-05-21 00:48 UTC, sprunk commented on LuaUI/Widgets/cmd_orbit.lua
> +			return cmd == CMD_ORBIT or cmd == CMD_ORBIT_DRAW or cmd == CMD_GUARD or cmd == CMD_AREA_GUARD
If you only look at the 1st command, prefer `Spring.GetUnitCurrentCommand` since that doesn't allocate two tables. Also, conventionally unit and command ID vars are called `unitID` and `cmdID`:
```suggestion
                IsUnitGuarding = function(unitID)
			local cmdID = Spring.GetUnitCurrentCommand(unitID)
			return cmdID == CMD_ORBIT or cmdID == CMD_ORBIT_DRAW or cmdID == CMD_GUARD or cmdID == CMD_AREA_GUARD
```

2024-05-21 00:48 UTC, sprunk commented on LuaUI/Widgets/cmd_orbit.lua
> +	        WG.Orbit.IsSelectionOverrideSet = self.value
some bad whitespace here
```suggestion
			WG.Orbit.IsSelectionOverrideSet = self.value
```

2024-05-21 00:48 UTC, sprunk commented on LuaUI/Widgets/cmd_orbit.lua
> +		name = "Global overrides selection rank",
```suggestion
		name = "Guard overrides selection rank",
```

2024-05-21 00:48 UTC, sprunk commented on LuaUI/Widgets/cmd_orbit.lua
> +		handler   = true,
I don't think `handler` should be needed?

2024-05-21 01:57 UTC, amnykon commented on LuaUI/Widgets/cmd_orbit.lua
> +		handler   = true,
I thought WG required it. Testing showed it didn't, so removing it.

2024-05-21 02:02 UTC, amnykon commented
Update PR to address Sprunk's comments.

2024-05-21 11:12 UTC, GoogleFrog commented
The PR lacks a description so I went looking for one.

> desc = "Units issued a guard command will be treated as a different selection rank.",
desc = "Units issued a guard command are treated as this selection rank, if override is enabled.",

I thought "this seems marginally more useful as an upper bound, rather than a strict override".

But then
```

		if WG.Orbit and WG.Orbit.IsSelectionOverrideSet and WG.Orbit.IsUnitGuarding(unitID) and (rank > WG.Orbit.SelectionOverrideRank) then
			rank = WG.Orbit.SelectionOverrideRank
		end
		```
So just make the description accurate?

2024-05-21 11:17 UTC, GoogleFrog commented
Hold up.

Why was the orbit widget modified at all? This should be a setting under selection rank, and it should work on guard regardless of whether the orbit widget is enabled. The WG-ness of the check for a guard command is redundant, as it doesn't ask the orbit widget anything. This entire PR should be in the selection rank widget, because the new option does nothing with selection rank disabled, and should do basically everything with orbit disabled.

2024-05-21 23:58 UTC, amnykon commented
updated to address GoogleFrog's comments, and removed the bool option since guardRankoverrideOption set at 3 is the same as having it off.

2024-05-22 08:22 UTC, GoogleFrog commented
Removing the tickbox option is nice too. But now, shouldn't the default be 3?

2024-05-22 18:01 UTC, amnykon commented
Updated default value to 3. As I just returned my new laptop due to too many crashes and boot issues, I am not able to currently test this change; however, it's simple enough that it should work, as long as the comma is still there.

2024-05-22 18:17 UTC, sprunk approved these changes
Already looks fine tho

2024-05-23 08:50 UTC, GoogleFrog commented on LuaUI/Widgets/gui_selection_hierarchy.lua
> +		end
I also like how the refactor encapsulates the behaviour within a check for the setting that controls the behaviour. It makes it more readable.

2024-05-23 08:53 UTC, GoogleFrog commented
I have yet had a chance to test, but I suspect the code has a bug. OnChanged doesn't call when the value is read as the default from settings, and the default is 3. However, the local value is 0, so guard selection rank will be applied until the player toggles it from 3 then back. I would remove `guardSelectionOverrideRank` to prevent this and future bugs like it, just use `options.<setting>.value`.

2024-05-24 03:09 UTC, amnykon commented
Updated, like I said, I returned my laptop so please test this before merging it. As the funds for my new laptop is allocated elsewhere, I cannot test until ~ December...

2024-05-27 01:32 UTC, sprunk commented on LuaUI/Widgets/gui_selection_hierarchy.lua
> +    local guardRankOverrideRank = settings.guardRankOverrideOption.value
```suggestion
    local guardRankOverrideRank = options.guardRankOverrideOption.value
```

2024-05-27 01:34 UTC, sprunk approved these changes

2024-05-27 01:35 UTC, sprunk commented
Tested, seems to work.

2024-06-08 06:45 UTC, merged